name: 'Build Plugin'
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/build.yaml@master
    with:
      dotnet-version: "8.0.x"
      dotnet-target: "net8.0"
